### ISSUE TITLE
Update Color Scheme plz

### ISSUE THREAD

**Issue by thecodechef** [karelvuong/st-primer#23]
So Sorry for but its just that when i'm in yml developing a new theme or color scheme it just looks weird

here take look
### Color Scheme Example

![screenshot from 2015-04-17 08 17 13](https://cloud.githubusercontent.com/assets/5333019/7202700/55f7876c-e4da-11e4-8c33-a6e2306661a9.png)
- Notice the after the part of the string it doesn't stay green i know its little but its annoying
### Theme Example

![screenshot from 2015-04-17 08 17 38](https://cloud.githubusercontent.com/assets/5333019/7202701/5883ac04-e4da-11e4-865c-3223965cc2f1.png)
- Notice When you define property like `layer0.opacity` you get the red colon i know its easily overlooked but can you fix this plz & thank you in advance

**Comment by thecodechef** [comment]
P.S you would happen to know where i can find a list of all the ui theme settings can change while developing a new theme would you

**Comment by ghost** [comment]
Hi @thecodechef, your comments have been addressed in order:
1. **String Quotations**:  this has been fixed in release v1.1.7
2. **YAML Colons**: I am unsure of what rule affects these colons. In the limited research I did, it doesn't look like other themes do as well. **If anyone has any insight into this, let me know or, better yet, submit a pull request!**
3. **List of UI Theme Settings**: This began as a fork of Spacegray's UI theme. I imagine that one exists somewhere, I am just not sure where.

Cheers!

**Comment by thecodechef** [comment]
Thanks Man
